### PR TITLE
meta-updater-qemux86-64/scripts/run-qemu is now obsolete and redundant.

### PR DESCRIPTION
**Pull request by pattivacek**
Use meta-updater/scripts/run-qemu-ota.

See also https://github.com/advancedtelematic/ats-garage-docs/pull/21

### CODE REVIEW

**Comment by tkfu** [comment]
Is this whole repo deprecated now @cajun-rat? If so, we should also update the readme, along with the readme in meta-updater which says that you need this as an extra layer.

**Comment by cajun-rat** [comment]
I'd like to phase it out, but I don't think it can be removed right now

**Comment by tkfu** [comment]
@patrickvacek How about making run-qemu a softlink to `../../meta-updater/scripts/run-qemu-ota` instead, just so we don't accidentally break anyone's workflow?

**Review by OYTIS — APPROVED** [review]

**Comment by pattivacek** [comment]
@tkfu @cajun-rat I actually had thought about that softlink idea, too, but can we rely on that working? Is it fair to assume that we can depend on the directory layout being stable enough to make that reliable?

**Comment by tkfu** [comment]
I think it's fair to assume that, yes. Anybody who is using this layer must also be using `meta-updater`, so the only way it would fail is if they did something really strange with where they put the layers, i.e. via manual download instead of using a repo manifest file.

**Comment by cajun-rat** [comment]
I'm happy with the soft-link idea.  If the link goes no-where, then at least people will be given a good clue as to where to find the tools

**Comment by pattivacek** [comment]
Done. Look okay?

**Review by tkfu — APPROVED** [review]

**Comment by cajun-rat** [comment]
Nice outcome :)

**Pull request merged**
