### PR TITLE
Add --efi option to boot via EFI bios

### PR DESCRIPTION
**Pull request by cajun-rat**

### CODE REVIEW

**Comment by OYTIS** [comment]
Looks good. Is this OVMF.fd shipped with QEMU or do we need to add it to our repo as well?

**Comment by cajun-rat** [comment]
It is in the 'ovmf' package, which is in Ubuntu, but not a dependency of qemu. I'll add a note to --help

**Comment by cajun-rat** [comment]
Updated

**Comment by cajun-rat** [comment]
Nudge :)

**Pull request merged**
