### PR TITLE
Revert "u-boot-ota_2015.07.bb: Use u-boot-ota from Pyro"

### PR DESCRIPTION
**Pull request by OYTIS**
This reverts commit d535ae698ef2643d4b6ecb72a85376b1966ab723.

See comments in advancedtelematic/meta-updater#215

### CODE REVIEW

**Comment by patrickvacek** [comment]
I get errors like this:

**Comment by patrickvacek** [comment]
Ignore my deleted comment about an error. That was my mistake.

**Comment by leon-anavi** [comment]
Just for the record: I believe this GitHub PR should hold until the issues in https://github.com/advancedtelematic/meta-updater/pull/232 are resolved and both should be merged simultaneously. Best regards, Leon

**Review by pattivacek — APPROVED** [review]
Should be good to go now.

**Pull request merged**
